
skillMetadata:
  sections:
    - name: Xbox WOL
      fields:
        - name: xbox_mac
          type: text
          label: Xbox MAC Address
          value: ""
          placeholder: XX:XX:XX:XX:XX:XX
